ThiHay/WebInterfaces/Thihay.User/Controllers/PracticeController.cs
using Microsoft.AspNetCore.Mvc;
using System.Threading.Tasks;
using Thihay.API.Client.Interfaces;
using Thihay.API.Client.Models;

namespace Thihay.User.Controllers
{
    public class PracticeController : BaseController
    {
        private readonly IEndUserService _service;
        private readonly string _token;
        public PracticeController(IEndUserService service, ITokenModel tokenModel)
        {
            _service = service;
            _token = tokenModel.AccessToken;
        }

        [HttpGet]
        [Route("practice/{id:int}")]
        public async Task<IActionResult> Index(int id)
        {
            if (!string.IsNullOrWhiteSpace(_token))
            {
                var unit = await _service.GetUnit(id);
                return View(unit);
            }
            ViewBag.Message = "Bạn phải đăng nhập để có thể làm bài kiểm tra này";
            return View();
        }

        [HttpGet]
        [Route("practice/getNextQuestion/{id:int}")]
        public IActionResult NextQuestion(int id)
        {
            if (!string.IsNullOrWhiteSpace(_token))
            {
                return ViewComponent("Question", id);
            }
            return RedirectToRoute("homepage");
        }

        [HttpPost]
        [Route("submitAnswer")]
        public async Task<IActionResult> SubmitAnswer([FromBody]Question question)
        {
            question.QuestionContent = question.QuestionContent ?? "";
            question.SubjectId = question.SubjectId ?? 0;
            question.ClassId = question.ClassId ?? 0;
            question.TopicId = question.TopicId ?? 0;
            question.UnitId = question.UnitId ?? 0;            
            var result = await _service.SubmitAnswer(question);
            return Ok(result);
        }
    }
}

ThiHay/WebInterfaces/Thihay.User/ViewComponents/KeypadViewComponent.cs
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace Thihay.User.ViewComponents
{
    public class KeypadViewComponent : ViewComponent
    {
        //private readonly IEndUserService _endUserService;
        //private readonly IIdentityService _identityService;
        //private readonly string _token;
        //public KeypadViewComponent(IEndUserService endUserService, IIdentityService identityService, ITokenModel token)
        //{
        //    _endUserService = endUserService;
        //    _token = token.AccessToken;
        //    _identityService = identityService;
        //}

        public async Task<IViewComponentResult> InvokeAsync()
        {
            
            return View();

        }
    }
}

ThiHay/WebInterfaces/Thihay.User/ViewComponents/QuestionViewComponent.cs
using Microsoft.AspNetCore.Mvc;
using System;
using System.Linq;
using System.Net;
using System.Text.RegularExpressions;
using System.Threading.Tasks;
using Thihay.API.Client.Interfaces;
using Thihay.API.Client.Models;
using Thihay.Common;
using Thihay.User.ViewModel;

namespace Thihay.User.ViewComponents
{
    [ViewComponent(Name = "Question")]
    public class QuestionViewComponent : ViewComponent
    {
        private readonly IEndUserService _endUserService;

        public QuestionViewComponent(IEndUserService endUserService)
        {
            _endUserService = endUserService;
        }

        public async Task<IViewComponentResult> InvokeAsync(int unitId)
        {
            var randomQuestion = await _endUserService.GetRandomQuestion(unitId, 0);
            if (randomQuestion != null)
            {
                randomQuestion.QuestionContent = WebUtility.HtmlDecode(randomQuestion.QuestionContent);
                switch (randomQuestion.QuestionType)
                {
                    case API.Client.QuestionType.MultipleChoice:
                        return MultipleChoiceViewComponent(randomQuestion);

                    case API.Client.QuestionType.ReadingComprehension:
                        return ReadingComprehensionViewComponent(randomQuestion);

                    case API.Client.QuestionType.FillInTheBlank:
                        return FillInTheBlankViewComponent(randomQuestion);

                    case API.Client.QuestionType.RewriteTheSentences:
                        return RewriteTheSentencesViewComponent(randomQuestion);

                    case API.Client.QuestionType.ClozeTest:
                        return ClozeTestViewComponent(randomQuestion);

                    case API.Client.QuestionType.Matching:
                        return MatchingViewComponent(randomQuestion);

                    case API.Client.QuestionType.Arrange:
                        return ArrangeViewComponent(randomQuestion);

                    case API.Client.QuestionType.DragAndDrop:
                        return DragAndDropViewComponent(randomQuestion);

                    case API.Client.QuestionType.Groups:
                        return GroupsViewComponent(randomQuestion);

                    case API.Client.QuestionType.Underline:
                        return UnderlineViewComponent(randomQuestion);

                    case API.Client.QuestionType.UnderlineAndRewrite:
                        return UnderlineAndRewriteViewComponent(randomQuestion);

                    case API.Client.QuestionType.DeleteCharacter:
                        return DeleteCharacterViewComponent(randomQuestion);

                    default:
                        break;
                }
            }
            return View();
        }

        private IViewComponentResult DeleteCharacterViewComponent(Question randomQuestion)
        {
            return View("DeleteCharacter");
        }

        private IViewComponentResult UnderlineAndRewriteViewComponent(Question randomQuestion)
        {
            return View("UnderlineAndRewrite");
        }

        private IViewComponentResult UnderlineViewComponent(Question randomQuestion)
        {
            var questionDetail = randomQuestion.QuestionDetail;
            randomQuestion.QuestionContent = Regex.Replace(randomQuestion.QuestionContent, @"\{(.*?)\}", "");
            foreach (var question in questionDetail)
            {
                var questionItem = question.QuestionDetailContent.Split(' ').Select(s =>
                {
                    var answerId = question.Answers.Where(a => a.AnswerContent == s).Select(a => a.AnswerId).FirstOrDefault();
                    return $"<span data-answer-id='{answerId}' class=\"p-type-10\" onclick=\"play_10(this)\">{s}</span>";
                });
                question.QuestionDetailContent = string.Join("", questionItem);
            }

            return View("Underline", randomQuestion);
        }

        private IViewComponentResult GroupsViewComponent(Question randomQuestion)
        {
            var groupQuestion = new GroupQuestionModel
            {
                QuestionId = randomQuestion.Id,
                QuestionType = randomQuestion.QuestionType,
                QuestionContent = randomQuestion.QuestionContent,
                QuestionExplanation = randomQuestion.QuestionExplanation,
                Questions = Helper.Shuffle(randomQuestion.QuestionDetail),
                Answers = Helper.Shuffle(randomQuestion.QuestionDetail.SelectMany(q => q.Answers).ToArray())
            };
            return View("Groups", groupQuestion);
        }

        private IViewComponentResult DragAndDropViewComponent(Question randomQuestion)
        {
            string content = randomQuestion.QuestionContent;
            Regex rgx = new Regex("{[0-9]+}");
            //string pattern = @"{.*}";
            string pattern = @"{[0-9]+}";
            Match m = Regex.Match(content, pattern);
            while (m.Success)
            {
                m = m.NextMatch();
            }

            foreach (var question in randomQuestion.QuestionDetail)
            {
                var questionRegx = question.QuestionDetailContent.Replace("{", @"\{").Replace("}", @"\}");
                var regex = new Regex(questionRegx);
                randomQuestion.QuestionContent = regex.Replace(randomQuestion.QuestionContent, $"<span data-question-id='{question.QuestionDetailId}' class=\"blank8\" ></span>", 1);
            }

            //var errorContentRgx = new Regex(@"\[vn\$(.*?)\$\]");
             //content8 = rgx.Replace(content8, "<input type=\"text\" class=\"blank8\" disabled value=\"\"></input>");
            //randomQuestion.QuestionContent = rgx.Replace(content, "<span class=\"blank8\" ></span>");
            randomQuestion.QuestionContent = randomQuestion.QuestionContent.Replace("[vn$", "").Replace("$]", "");

            return View("DragAndDrop", randomQuestion);
        }

        private IViewComponentResult ArrangeViewComponent(Question randomQuestion)
        {
            randomQuestion.QuestionDetail = Helper.Shuffle(randomQuestion.QuestionDetail.ToArray());
            return View("Arrange", randomQuestion);
        }

        private IViewComponentResult MatchingViewComponent(Question randomQuestion)
        {
            var machingQuestion = randomQuestion.QuestionDetail.Select(q => new
            {
                Question = new QuestionDetail
                {
                    Id = q.Id,
                    QuestionDetailContent = q.QuestionDetailContent,
                    QuestionDetailId = q.QuestionDetailId,
                    QuestionId = q.QuestionId
                },
                Answer = new Answer
                {
                    AnswerContent = q.Answers.FirstOrDefault().AnswerContent,
                    AnswerId = q.Answers.FirstOrDefault().AnswerId,
                    AnswerIndex = q.Answers.FirstOrDefault().AnswerIndex,
                    IsCorrectAnswer = q.Answers.FirstOrDefault().IsCorrectAnswer
                }
            });
            var left = machingQuestion.Select(q => q.Question).ToArray();
            var right = machingQuestion.Select(q => q.Answer).ToArray();
            left = Helper.Shuffle(left).ToArray();
            right = Helper.Shuffle(right).ToArray();
            return View("Matching", new MatchingQuestion
            {
                QuestionId = randomQuestion.Id,
                QuestionContent = randomQuestion.QuestionContent,
                QuestionExplanation = randomQuestion.QuestionExplanation,
                QuestionType = randomQuestion.QuestionType,
                Question = left,
                Answer = right
            });
        }

        private IViewComponentResult ClozeTestViewComponent(Question randomQuestion)
        {
            randomQuestion.QuestionContent = randomQuestion.QuestionContent.Replace("->", "<i class='fa fa-hand-o-right' aria-hidden='true'></i>");
            var questionContent = randomQuestion.QuestionContent;
            foreach (var node in randomQuestion.QuestionDetail)
            {
                string dropdown = $"<select class='ThSelect' data-question-detail-id='{node.QuestionDetailId}'>";
                dropdown += string.Join("", node.Answers.Select(s =>
                {
                    var answer = s.AnswerContent.Replace("\"", "&quot;");
                    return $"<option value='{s.AnswerId}'>{s.AnswerContent}</option>";
                }));
                dropdown += "</select>";
                questionContent = Helper.ReplaceFirst(questionContent, "{}", dropdown);
            }
            randomQuestion.QuestionContent = questionContent;



            return View("ClozeTest", randomQuestion);
        }

        private IViewComponentResult RewriteTheSentencesViewComponent(Question randomQuestion)
        {
            return FillInTheBlankViewComponent(randomQuestion);
        }

        private IViewComponentResult FillInTheBlankViewComponent(Question randomQuestion)
        {
            //var regex = @"\{(.*?)\}";
            Regex rgx = new Regex("{}");
            //            while (rgx.IsMatch(randomQuestion.QuestionContent))
            //            {
            //                var guid = Guid.NewGuid();
            //                randomQuestion.QuestionContent = rgx.Replace(randomQuestion.QuestionContent, $@"
            //<span class ='input-math' data-answer-guid='{guid}' id='math-field-{guid}'></span>
            //<input type='hidden' id='value-field-{guid}'>", 1);
            //            }
            bool isMath = false;
            var questionDetails = randomQuestion.QuestionDetail;
            foreach (var question in questionDetails)
            {
                var questionDetailId = question.QuestionDetailId;

ThiHay/WebInterfaces/Thihay.User/Views/Practice/Index.cshtml
@model Thihay.API.Client.Models.Unit
@{
    var message = ViewBag.Message != null ? (string)ViewBag.Message : string.Empty;
}
<div id="popup">
    <div id="dialog">
        <div id="icon" class="label-dialog"></div>
        <div class="body-dialog">
            <p class="animated"></p>
        </div>
    </div>
</div>

<section class="box-violympic-10">
    <div class="container">
        <div class="block-11">
            <ul class="nav-tab">
                <li>
                    <a href="#" class="tablinks" title="" onclick="openTab(event, 'practice-tab')" id="defaultOpen">Luyện Tập</a>
                </li>
                <li>
                    <a href="#" class="tablinks" onclick="openTab(event, 'description-tab')">Lý Thuyết</a>
                </li>
            </ul>
        </div>
        @*<div class="tab">
                <button class="tablinks" onclick="openTab(event, 'practice-tab')" id="defaultOpen">Luyện Tập</button>
                <button class="tablinks" onclick="openTab(event, 'description-tab')">Lý Thuyết</button>
            </div>*@
        <div class="row tabcontent" id="practice-tab">
            @if (Model != null)
            {
                <div class="col col-900">
                    <div class="page-header">
                        <h1 id="name-unit" style="font-size: 36px; line-height: 1.25;">@Html.Raw(Model.NameUnit)</h1>
                    </div>
                    <div class="block-19">
                        <div id="play-content">
                            @await Component.InvokeAsync("Question", Model.Id)
                        </div>
                        <div class="handle">
                            <button type="button" id="submit" class="btn-submit">Nộp bài</button>
                        </div>
                    </div>
                </div>
                <input type="hidden" id="unit-id" value="@Model.Id" />
            }
            <div class="col col-180">
                <div class="block-20">
                    <div class="answer"><span>Số câu đã trả lời</span></div>
                    <div class="reply" id="count-180">0</div>
                    <div class="elapsed">Thời gian làm bài</div>
                    <div class="status">
                        <div class="pause" style="display:none;">PAUSE</div>
                        <div class="row">
                            <div class="col">
                                <div class="time">
                                    <div class="inner">
                                        <div class="wrap">
                                            <div class="number" id="hours">00</div>
                                        </div>
                                    </div>
                                </div>
                                <div class="text">Giờ</div>
                            </div>
                            <div class="col">
                                <div class="time">
                                    <div class="inner">
                                        <div class="wrap">
                                            <div class="number" id="minutes">00</div>
                                        </div>
                                    </div>
                                </div>
                                <div class="text">Phút</div>
                            </div>
                            <div class="col">
                                <div class="time">
                                    <div class="inner">
                                        <div class="wrap">
                                            <div class="number" id="seconds">00</div>
                                        </div>
                                    </div>
                                </div>
                                <div class="text">Giây</div>
                            </div>
                            <input type="hidden" value="0" id="timer-in-second" />
                        </div>
                    </div>
                    <div class="score"><span>Điểm</span></div>
                    <div class="reply" id="info-score">0</div>
                </div>
            </div>
        </div>
        <div class="row tabcontent" id="description-tab">
            <div class="col col-900">
                <div class="page-header">
                    <h1 style="font-size: 36px; line-height: 1.25;">Lý Thuyết</h1>
                </div>
                <div class="block-19">
                    <p>
                        @Html.Raw(Model.DescriptionUnit)
                    </p>

                </div>
            </div>
        </div>
        <div id="getmark" style="display:none;">
        </div>
    </div>
    @await Component.InvokeAsync("Keypad")
    @if (Model == null)
    {
        <script type="text/javascript">
            AlertRedirect("@message", "/login");
        </script>
    }
    else
    {
        <script type="text/javascript">
            document.getElementById("defaultOpen").click();
            TimeUp();
            $("#explanation").hide();
            $(".btn-submit").on("click", function () {
                $("#math-key-pad").css("visibility", "hidden");
                var questionType = $("#question-type").val();
                processQuestion(questionType, function (correctCnt, message) {
                    var unitId = $("#unit-id").val();
                    var questionAnswerd = parseInt($("#count-180").text());
                    questionAnswerd++;
                    $("#count-180").text(questionAnswerd);
                    var score = parseInt($("#info-score").text());
                    score = score + correctCnt;
                    $("#info-score").text(score);
                    AlertNoRedirect(message);
                    $('#play-content').load("/practice/getNextQuestion/" + unitId, function () {
                        $("#explanation").hide();
                        $("#exams").click(function () {
                            if ($(".mq-focused").length) {
                                ID = $(".mq-focused").attr("id");
                                console.log(ID);
                            }
                        });
                    });
                });
                console.log(questionType);

            });
            var ID = "";
            $("#exams").click(function () {
                if ($(".mq-focused").length) {
                    ID = $(".mq-focused").attr("id");
                    console.log(ID);
                }
            });
            $(".key-pad-btn").on("click", function () {
                var val = $(this).find('input').val();
                if (ID != "") {
                    var mathFieldSpan = document.getElementById(ID);
                    var mathField = MQ.MathField(mathFieldSpan, {
                        spaceBehavesLikeTab: true
                    });
                    var curr = mathField.latex();
                    txt = curr + val;
                    mathField.typedText(val);
                }
            });


            function openTab(evt, tablId) {
                // Declare all variables
                var i, tabcontent, tablinks;

                // Get all elements with class="tabcontent" and hide them
                tabcontent = document.getElementsByClassName("tabcontent");
                for (i = 0; i < tabcontent.length; i++) {
                    tabcontent[i].style.display = "none";
                }

                // Get all elements with class="tablinks" and remove the class "active"
                tablinks = document.getElementsByClassName("tablinks");
                for (i = 0; i < tablinks.length; i++) {
                    tablinks[i].className = tablinks[i].className.replace(" active", "");
                }

                // Show the current tab, and add an "active" class to the button that opened the tab
                document.getElementById(tablId).style.display = "block";
                evt.currentTarget.className += " active";
            }


        </script>

    }
</section>
<style>


</style>